services:
  # Main application (backend + frontend)
  notifier:
    image: docker.io/billos/tmars-notifier:1.4.0
    ports:
      - "3000:3000"
    command: ["start:backend"]
    env_file:
      - .env
    environment:
      NODE_ENV: production
      LOG_LEVEL: 2
    restart: unless-stopped
    depends_on:
      - redis

  # Redis service
  redis:
    image: redis:7-alpine
    restart: unless-stopped

volumes:
  redis_data:

